name: Publish documentation

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cargo:
    uses: majksa-actions/workflows/.github/workflows/rust-docs.yml@v1
